spring.application.name=securityjwt
# App settings
server.port=8080

# JWT settings (if you use)
jwt.secret=secret123
jwt.expiration=3600000

# Logging
logging.level.org.springframework.security=DEBUG

